# This workflow will build a .NET project and create a release

name: Releaser

on:
  push:
    branches: [ "main" ]


jobs:
  build:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          body: |
            Automating release
          draft: false
          prerelease: false
          working-directory: ProxyDLLApp