# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SLN_ABSPATH: "${{ github.workspace }}/ProxyDLLApp"
  PROJECT_NAME: "ProxyDLL"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore $SLN_ABSPATH
    - name: Build
      run: dotnet build --no-restore $SLN_DIR
    - name: Test
      run: dotnet test --no-build --verbosity normal $SLN_DIR
    - name: Run the application
      run: dotnet run --project "$SLN_ABSPATH/$PROJECT_NAME" "$SLN_ABSPATH/artifcat.txt" "This is a legit workflow"
    - uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: "$SLN_ABSPATH/artifcat.txt"
