# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SLN_ABSPATH: "${{ github.workspace }}/ProxyDLLApp"
  PROJECT_NAME: "ProxyDLL"
  ARTIFACT_DIR: "/tmp/artifacts"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Create artifact dir
      run: mkdir -p "$ARTIFACT_DIR"
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore $SLN_ABSPATH
    - name: Debug command
      run: ls "${{ github.workspace }}"
    - name: Run the application
      run: dotnet run --project "$SLN_ABSPATH/$PROJECT_NAME" "$ARTIFACT_DIR/artifact.txt" "This is a legit workflow"
    - uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        overwrite: true
        path: "/tmp/artifacts"
